language: scala
scala:
- 2.11.7
sudo: false
jdk:
- oraclejdk8
env:
  global:
    - GIT_COMMITTER_NAME=cncgl
    - GIT_COMMITTER_EMAIL=concigel@gmail.com
    - GIT_AUTHOR_NAME=cncgl
    - GIT_AUTHOR_EMAIL=concigel@gmail.com
    - secure: ZPtn4qWsMraYIrG3VQxrI9r8HRkzGPmclKZozcwXpwvW0TrU9N2+ZUv/qIX6lOGA9eZesJW8hnZ8DF5c7MJ7329YCKJpwVhKRbzeN5+sCe5f7yLzfqaARFnov6GgmaFc0jhrETCgCzEiPMpYlSmvNXTRPNrkbx7P6m8E3sehiMhiwsYNYoZzJeaQS3ZMXmZ02nKjFc8ayW/SDDfLUl7qNBgsdTngFza7+MZmTz6+fCGP9nze5L7ziB2HDLO8emWQ2BuHK9lIEPBXelk1AE1FUfg5KLc1Qa11Nn39hAi8Mdvgo7ZJI2bgMihgyz2i9SmifCGO+lg8NS3RLENDLix6zyfRZoSROaqQZpq1fDLKhFGpPhfe5HWUJaU82pMiPhIcl6N36yQ64DDcvQofYMirlk3aOiHyDZ2YSl40YzluZy2jmJkGPtkBPxq/nv63HRPRO9cD0dmpbp+Acxz3UeCf9yK/jR1VxlZ7yYhWpXuAI5j48gfCUd68tKXdkNJE6HwX0t5QgRTdWpPF9etl7MFGAoAk4f3Mxwl4DgpS4uKiZC7gvuML0uQ7XlcDLF3jcz2JGO1CWQTbhkTDNvV/0TSlffqcD4qPPASAoCfTv6eZbRWQ7SuJqP9AgiD5foYrN5nmSJQvKt8jOPofcJtwKrLD1NX49Z6r+kSFuxWilqg25dc=
script:
- sbt ++$TRAVIS_SCALA_VERSION fullOptJS test
# Tricks to avoid unnecessary cache updates, from
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- mkdir dist
- cp *.html dist
- cp -r target dist
- cd dist
- git init
- git add -A
- git commit -m 'Deploy to GitHub Pages'
- '[ $GH_TOKEN ] && git push --force --quiet https://$GH_TOKEN@github.com/cncgl/scalajs-tutorial.git master:gh-pages 2> /dev/null'
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
